on: push
name: Website deployment on HelioHost
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 65.19.141.67
        username: milobretet
        password: ${{ secrets.ftp_password }}
        server-dir: httpdocs/